# Generated by Django 3.1.7 on 2021-03-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='Segundo E-mail')),
                ('data_hora', models.DateTimeField()),
            ],
        ),
    ]
