# Generated by Django 3.1.7 on 2021-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='agendamento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='enviar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
