# Generated by Django 3.1.7 on 2021-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210301_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='agendamento',
            field=models.DateField(null=True),
        ),
    ]
